{{- if .Values.ingress.enabled -}}
{{ $adminServiceName := printf "%s" .Values.fullnameOverride  | trunc 63 | trimSuffix "-" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {{ $fullname := printf "%s" .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $adminServiceName }}
                port:
                  name: http
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}