{{- if .Values.components.admin.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Values.fullnameOverride "admin" | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}
    app.kubernetes.io/component: admin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.fullnameOverride }}
      app.kubernetes.io/component: admin
  replicas: {{ default 1 .Values.components.admin.replicaCount | int }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Values.fullnameOverride }}
        app.kubernetes.io/component: admin
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.components.admin.image.registry }}/{{ .Values.components.admin.image.repository }}:{{ .Values.components.admin.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: API_GATEWAY_SERVER
          value: {{ .Values.components.admin.apiGatewayServer | quote }}
        ports:
        - containerPort: {{ .Values.components.admin.containerPorts.http | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.components.admin.containerPorts.http | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.components.admin.containerPorts.http | int }}
        resources:
{{ toYaml .Values.components.admin.resources | indent 10 }}
{{- end -}}